name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzE2MDUyNWEtNDhjNS00ZDQxLWE2NTItMjRhZDRjZjgyOGI2IiwidGVuYW50X2lkIjoiMTcyMWQ2Mzk2NmMzYjdlNTQyMWY3MTA3ZGJkOTczZDIzOTg4YTIxNGU3YjZiY2M1MDVjYWU3ZGIzNTJiZjc0ZiIsImludGVybmFsX3NlY3JldCI6ImNjYTc5MjBlLWZiMzItNDNkYi1hMmJiLTdjYWE0ODUyODgzYiJ9.MKzV6G_BGrI_QJC480PzwygL80X1HTPR7Pn5P4VyuAQ"
JWT_SECRET = "Shubham123"